<a href="https://colab.research.google.com/github/meliksahb/CV-with-Tensorflow/blob/main/firstTraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d) # this will output <tf.Tensor: shape=(), dtype=int32, numpy=4>

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2,0,-3, 8, 90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [6]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [2,5,6],
    [2,3,8],
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 2  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[10,2,0],
    [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [9]:
print(tensor_three_d.ndim)  # To check dimension

3


In [12]:
tensor_four_d = tf.constant([
   [[[1,2,0],
    [3,5,-1]],
    [[10,2,0],
    [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]],
   [[[13,24,0],
    [33,54,-1]],
    [[10,2,5],
    [1,0,23]],
    [[52,8,0],
     [42,73,0]],
    [[24,1,93],
     [46,-33,32]]]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 13  24   0]
   [ 33  54  -1]]

  [[ 10   2   5]
   [  1   0  23]]

  [[ 52   8   0]
   [ 42  73   0]]

  [[ 24   1  93]
   [ 46 -33  32]]]], shape=(2, 4, 2, 3), dtype=int32)


In [11]:
print(tensor_four_d.ndim)

4


In [16]:
tensor_one_d2 = tf.constant([2,0,-3, 8, 90.], dtype=tf.float32)
casted_tensor_one_d2 = tf.cast(tensor_one_d2, dtype=tf.int16)  # changes the type
casted_2_tensor_one_d2 = tf.cast(tensor_one_d2, dtype=tf.bool)  # all the values different from 0 True, else False
print(tensor_one_d2)
print(casted_tensor_one_d2)
print(casted_2_tensor_one_d2)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [17]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [19]:
tensor_string = tf.constant(["Hello", "World", "A"])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'A'], shape=(3,), dtype=string)


In [22]:
import numpy as np

In [21]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [23]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [30]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 5, 3), dtype=float32)
tf.Tensor(
[[[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 5, 3), dtype=float32)


In [31]:
eye_tensor2 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor2)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [33]:
fill_tensor = tf.fill(
    [3,4,5],
    9,
    name=None
)
print(fill_tensor)

tf.Tensor(
[[[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]], shape=(3, 4, 5), dtype=int32)


In [38]:
ones_tensor = tf.ones(
    [2,5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 5, 3), dtype=float32)


In [40]:
ones_like_tensor = tf.ones_like(  # creates a tensor of all ones that has the same shape as the input
    fill_tensor,
    dtype=None,
    name=None
)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(3, 4, 5), dtype=int32)


In [42]:
zeros_tensor = tf.zeros(
    [2,5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 5, 3), dtype=float32)


In [43]:
shape_tensor = tf.shape(fill_tensor,)  # returns a tensor containing the shape of the input tensor
print(shape_tensor)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [44]:
rank_tensor = tf.rank(fill_tensor)  # returns the rank of the input tensor
print(rank_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [48]:
size_tensor = tf.size(fill_tensor, out_type=tf.float32)  # returns the size of the input tensor
print(size_tensor)

tf.Tensor(60.0, shape=(), dtype=float32)


In [51]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.79385 100.54894]
 [ 98.35695  99.07928]
 [100.17673  99.6454 ]], shape=(3, 2), dtype=float32)
